/*CREATE ROLE R_EXAMEN2020;
CREATE ROLE R_CORRIGE;
CREATE USER FSExxx identified by password;
GRANT R_EXAMEN2020, CONNECT, CREATE TABLE, CREATE VIEW TO
FSExxx;
GRANT SELECT, UPDATE (RESPUESTA) ON FIS2020.V_PREGUNTAS TO
R_EXAMEN2020;*/
--Hecho por el porfesor

--Enunciado 1
CREATE TABLE MARCA(
"IDMARCA" NUMBER,
"NOMBRE" VARCHAR2(50 BYTE),
"PRECIOHORA" NUMBER(6,2)
)TABLESPACE TS_EXAMEN2020 PCTFREE 10;

--Enunciado 2
CREATE TABLE MODELO(
"IDMODELO" NUMBER,
"MARCA_IDMARCA" NUMBER,
"NOMBRE" VARCHAR2(100),
"NUMPUERTAS" NUMBER,
"COMBUSTIBLE" VARCHAR2(64),
"CAPACMALETERO" NUMBER
)TABLESPACE TS_ALUMNOS PCTFREE 15;

--Enunciado 3
ALTER TABLE MARCA ADD CONSTRAINT PK_MARCA PRIMARY KEY(IDMARCA);
ALTER TABLE MODELO ADD CONSTRAINT PK_MODELO PRIMARY KEY(IDMODELO);
ALTER TABLE MODELO ADD CONSTRAINT FK_MARCA_MODELO FOREIGN KEY(MARCA_IDMARCA) REFERENCES MARCA;
SELECT * FROM USER_TS_QUOTAS;
ALTER INDEX PK_MARCA REBUILD TABLESPACE TS_PI;
ALTER INDEX PK_MODELO REBUILD TABLESPACE TS_PI;
SELECT * FROM ALL_INDEXES WHERE TABLESPACE_NAME = 'TS_PI';/*COMPROBAR QUE ESTÁN AHÍ*/

--Enuenciado 4
CREATE INDEX IDX_MOD_COMBUSTIBLE ON MODELO(COMBUSTIBLE);
CREATE UNIQUE INDEX IDX_MARCA_NOMBRE ON MARCA(NOMBRE) TABLESPACE TS_ALUMNOS;
CREATE BITMAP INDEX IDX_MOD_MARCA ON MODELO(MARCA_IDMARCA);
CREATE INDEX IDX_MOD_MAYUS ON MODELO(UPPER(NOMBRE));

--Enunciado 5
GRANT UPDATE(CAPACMALETERO)ON MODELO TO R_CORRIGE;
GRANT SELECT ON MODELO TO R_CORRIGE;
CREATE VIEW V_MODELO AS SELECT IDMARCA , NOMBRE FROM MARCA;

--Enunciado 6
select * from fis2020.v_preguntas;
SELECT * FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_PUERTAS';
update fis2020.v_preguntas set respuesta = 'SELECT * FROM ALL_INDEXES WHERE INDEX_NAME = IDX_PUERTAS(COMILLAS); Y no sale nada'
where id = 1;

SELECT * FROM USER_USERS;
update fis2020.v_preguntas set respuesta = 'TS_PI'
where id = 2;

select * from v$datafile; 

update fis2020.v_preguntas set respuesta = '/u01/app/oracle/product/18.0.0/dbhome_1/dbs/examen2020.dbf'
where id = 3;









